-- ══════════════════════════════════════════════════════════════
-- أصولُ البناء — 0004 : بذرةُ الكتالوج
--
-- ثمانيةٌ وعشرون منتجًا **مولَّدةٌ من `inc/catalog.php`** لا مكتوبةٌ
-- بيد: أبواب 6 · جبسوم 13 · Strut 9. فالنقلُ الذي يُعاد فيه
-- إدخالُ البيانات يدويًّا يُدخل خطأً لا يظهر إلّا عند الزبون.
--
--     ما يُنسَخ آليًّا لا يُخطئ فيه ناسخ.
--
-- و`image_url` يشير اليومَ إلى `wp-content/uploads` على ووردبريس —
-- وهو ما سيُطفأ. فنقلُ الصور إلى التخزين شرطُ الإطفاء، لا زينةً
-- بعده (م٨).
--
-- والسعرُ ليس هنا: `product_prices` جدولٌ آخر، لا يقرؤه إلّا المدير.
-- وهذا هو الثابتُ ② ماثلًا في البذرة نفسِها.
-- ══════════════════════════════════════════════════════════════

insert into public.products
  (slug, group_key, name_ar, name_en, sub_ar, sub_en,
   badge_ar, badge_en, image_url, specs_ar, specs_en, sort)
values
  ('fire-resistant-doors', 'doors', 'الأبواب المعدنية المقاومة للحريق', 'Fire-Resistant Metal Doors', 'معتمدة من 30 إلى 120 دقيقة', 'Rated 30 to 120 minutes', 'الأكثر طلباً', 'Best Seller', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/ابواب-الطوارئ.png', array['مقاومة الحريق: 30-120 دقيقة','سماكة الصفيح: 1.2-2.0 مم','إطار مجلفن مزدوج','مزودة بنظام إغلاق تلقائي']::text[], array['Fire rating: 30–120 min','Sheet thickness: 1.2–2.0 mm','Double galvanized frame','Equipped with automatic closing']::text[], 10),
  ('hollow-metal-doors', 'doors', 'الأبواب المعدنية المجوفة', 'Hollow Metal Doors', 'تصميمات متعددة للمباني التجارية', 'Multiple designs for commercial buildings', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/ابواب-حديد.png', array['سماكة الصفيح: 1.0-1.6 مم','ملء اختياري: هانيكوم أو مواد عازلة','إطار مجلفن أو ملون','متوفرة بمقاسات مخصصة']::text[], array['Sheet: 1.0–1.6 mm','Fill: honeycomb or insulation','Galvanized or painted frame','Custom sizes available']::text[], 20),
  ('cladding-doors', 'doors', 'الأبواب التكسوية', 'Cladding Doors', 'تكسوة معدنية أو HPL أو زجاجية', 'Metal, HPL or glass cladding', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/ابواب-كلادينج-تركي.png', array['تكسوة: معدن، HPL، زجاج','نواة: صلب مجوف أو EPS','سهلة التنظيف','مظهر معماري مميز']::text[], array['Cladding: metal, HPL, glass','Core: hollow steel or EPS','Easy to clean','Distinctive architectural look']::text[], 30),
  ('mdf-doors', 'doors', 'الأبواب الخشبية MDF', 'MDF Wooden Doors', 'للوحدات السكنية والتجارية', 'For residential & commercial units', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/ابواب-تركي-ام-دي-اف.png', array['مادة: MDF عالي الكثافة','أوجه متعددة: مرايا، خشب، دهان','بمقاسات قياسية ومخصصة','متوفر مع إطار خشبي أو معدني']::text[], array['Material: high-density MDF','Faces: mirror, wood, paint','Standard & custom sizes','Available with wood or metal frame']::text[], 40),
  ('wpc-doors', 'doors', 'الأبواب WPC مقاومة الرطوبة', 'WPC Moisture-Resistant Doors', 'للحمامات والمناطق الرطبة', 'For bathrooms & wet areas', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/ابواب-ببليو-بي-سي.png', array['مادة: WPC (خشب-بلاستيك)','مقاوم للرطوبة 100%','لا يتآكل ولا يتشوه','ألوان وأنماط متعددة']::text[], array['Material: WPC (wood-plastic)','100% moisture resistant','No corrosion or deformation','Multiple colors & patterns']::text[], 50),
  ('custom-doors', 'doors', 'الأبواب المخصصة', 'Custom Doors', 'وفق مواصفات العميل والمشروع', 'Per client and project specs', 'مخصص', 'Custom', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/تفصيل-حسب-الطلب.png', array['تصنيع حسب الطلب','متطلبات حريق مخصصة','أبعاد وأشكال غير قياسية','ألوان ومواد حسب العميل']::text[], array['Made to order','Custom fire requirements','Non-standard dimensions & shapes','Colors & materials per client']::text[], 60),
  ('c-stud-25', 'gypsum', 'C-Stud 25 مم', 'C-Stud 25 mm', 'للجدران الخفيفة الداخلية', 'For lightweight interior partitions', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/098900899.png', array['الحجم: 25×50 مم','السماكة: 0.45 مم','الطول: 3-4 متر','مجلفن سماكة Z120']::text[], array['Size: 25×50 mm','Thickness: 0.45 mm','Length: 3-4 m','Z120 galvanized']::text[], 70),
  ('c-stud-50', 'gypsum', 'C-Stud 50 مم', 'C-Stud 50 mm', 'للجدران المتوسطة', 'For medium partition walls', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/098900899.png', array['الحجم: 50×50 مم','السماكة: 0.5-0.6 مم','الطول: 3-5 متر','مجلفن سماكة Z120']::text[], array['Size: 50×50 mm','Thickness: 0.5–0.6 mm','Length: 3–5 m','Z120 galvanized']::text[], 80),
  ('c-stud-75', 'gypsum', 'C-Stud 75 مم', 'C-Stud 75 mm', 'للجدران العازلة الأكبر', 'For larger insulation walls', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/098900899.png', array['الحجم: 75×50 مم','السماكة: 0.55-0.7 مم','الطول: 3-6 متر','مجلفن سماكة Z120']::text[], array['Size: 75×50 mm','Thickness: 0.55–0.7 mm','Length: 3–6 m','Z120 galvanized']::text[], 90),
  ('u-track', 'gypsum', 'U-Track تراك تثبيت', 'U-Track', 'لتثبيت C-Stud في الأرضية والسقف', 'For fixing C-Stud to floor and ceiling', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/778789899.png', array['أبعاد: 25/50/75 مم','السماكة: 0.45 مم','الطول: 3 متر','مجلفن Z120']::text[], array['Sizes: 25/50/75 mm','Thickness: 0.45 mm','Length: 3 m','Z120 galvanized']::text[], 100),
  ('l-angle', 'gypsum', 'L-Angle زاوية التشطيب', 'L-Angle Corner Bead', 'لتشطيب حواف الجبسوم بورد', 'For finishing gypsum board edges', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/3677578.png', array['القياس: 25×25 مم أو 30×30 مم','السماكة: 0.4 مم','الطول: 3 متر','مجلفن أو مطلي بالزنك']::text[], array['Size: 25×25 or 30×30 mm','Thickness: 0.4 mm','Length: 3 m','Galvanized or zinc-coated']::text[], 110),
  ('hat-channel', 'gypsum', 'Hat Channel قبعة', 'Hat Channel', 'للأسقف المصطنعة والجدران', 'For suspended ceilings and walls', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/65477657.png', array['الحجم: 50×17 مم أو 60×20 مم','السماكة: 0.45 مم','الطول: 3 متر','مجلفن Z120']::text[], array['Size: 50×17 or 60×20 mm','Thickness: 0.45 mm','Length: 3 m','Z120 galvanized']::text[], 120),
  ('main-ceiling-channel', 'gypsum', 'Main Channel قناة السقف', 'Main Ceiling Channel', 'قناة السقف الرئيسية', 'Primary ceiling support channel', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/647676767.png', array['الحجم: 50×28 مم أو 60×27 مم','السماكة: 0.5-0.6 مم','الطول: 3-4 متر','مجلفن Z120']::text[], array['Size: 50×28 or 60×27 mm','Thickness: 0.5–0.6 mm','Length: 3–4 m','Z120 galvanized']::text[], 130),
  ('gypsum-accessories', 'gypsum', 'إكسسوارات الجبسوم', 'Gypsum Board Accessories', 'كامل إكسسوارات نظام الجبسوم', 'Complete gypsum system accessories', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/٦٥٦٥٧٥٦.png', array['خيوط تقوية','إكسسوارات تعليق','مسامير وبراغي خاصة','إكسسوارات حواف ومنافذ']::text[], array['Reinforcement tape','Suspension accessories','Special screws & fixings','Edge & outlet accessories']::text[], 140),
  ('u-clip', 'gypsum', 'U-Clip يوكليب', 'U-Clip', 'تثبيت الشبكة الثانوية على C-Channel', 'Fixes secondary grid to C-Channel', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/77667888.png', array['المادة: صلب مجلفن','السماكة: 0.5 مم','سهل التركيب والتثبيت','مناسب لجميع أحجام C-Channel']::text[], array['Material: galvanized steel','Thickness: 0.5 mm','Easy installation','Compatible with all C-Channel sizes']::text[], 150),
  ('wire-clip', 'gypsum', 'Wire Clip واير كليب', 'Wire Clip', 'ربط أسلاك التعليق بـ C-Channel', 'Connects suspension wires to C-Channel', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/9877678887.png', array['المادة: صلب مجلفن','السماكة: 2.5 مم','قوة تحمل عالية','سهولة الضبط والتركيب']::text[], array['Material: galvanized steel','Thickness: 2.5 mm','High load capacity','Easy adjustment and installation']::text[], 160),
  ('angel-w20', 'gypsum', 'زاوية دبليو 20×20 مم', 'Angle W20×20 mm', 'زاوية تشطيب للحواف الداخلية', 'Finishing angle for internal edges', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/666554466.png', array['القياس: 20×20 مم','السماكة: 0.35-0.6 مم','الطول: 3-6 متر','مجلفن Z120']::text[], array['Size: 20×20 mm','Thickness: 0.35-0.6 mm','Length: 3-6 m','Z120 galvanized']::text[], 170),
  ('angel-w30', 'gypsum', 'زاوية دبليو 20×30 مم', 'Angle W20×30 mm', 'زاوية تشطيب للحواف الخارجية', 'Finishing angle for external edges', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/7679898787.png', array['القياس: 20×30 مم','السماكة: 0.35-0.6 مم','الطول: 3-6 متر','مجلفن Z120']::text[], array['Size: 20×30 mm','Thickness: 0.35-0.6 mm','Length: 3-6 m','Z120 galvanized']::text[], 180),
  ('shadow-angle', 'gypsum', 'زاوية الضلال Shadow', 'Shadow Angle', 'تأثير Shadow Line على حواف الأسقف والجدران', 'Shadow line effect on ceiling and wall edges', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/09987767899.png', array['السماكة: 0.4-0.6 مم','الطول: 3-6 متر','لإنشاء خط الظل المعماري','مجلفن Z120']::text[], array['Thickness: 0.4-0.6 mm','Length: 3-6 m','Creates architectural shadow line','Z120 galvanized']::text[], 190),
  ('u-bolt-etr-l', 'strut', 'طوق U بخيط طويل ETR-L', 'U-Bolt ETR-L', 'تثبيت مباشر للأنابيب على قنوات FUS', 'Direct pipe fastening to FUS channels', 'الأكثر مبيعاً', 'Best Seller', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/U-bolt-ETR-L.png', array['أقطار خارجية: 21 - 324 مم','مادة: فولاذ مجلفن','متوافق مع قنوات FUS 41 وأذرع FCA','يعدل بمسامير وصواميل مرفقة','للاستخدام الداخلي الجاف فقط']::text[], array['Outer diameter: 21-324 mm','Material: galvanized steel','Compatible with FUS 41 channels','Adjustable with supplied screws','For dry indoor use only']::text[], 200),
  ('u-bolt-connector-fetr-c', 'strut', 'وصلة قناة FETR-C', 'U-Bolt Connector FETR-C', 'توصيل أطواق ETR بقنوات FUS', 'Connect ETR U-Bolts to FUS channels', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/U-bolt-ETR-L.png', array['تمركز حر بدون قيد الثقوب','مادة: فولاذ S235JR مجلفن','يتصل بـ FCN Clix P وSKS','صامولتان اضافيتان لتوصيل ETR']::text[], array['Free positioning regardless of holes','Material: steel S235JR galvanized','Via FCN Clix P and SKS screws','2 additional nuts for ETR']::text[], 210),
  ('channel-fls', 'strut', 'قناة FLS للتثبيت الخفيف', 'Channel FLS', 'العنصر الاساسي لنظام FLS المرن', 'Base element of the flexible FLS system', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/Channel-FLS.png', array['ارتفاعات: 17 / 30 / 37 مم','مادة: فولاذ S250GD مجلفن','اطوال: 2 / 3 / 6 متر','شهادة حريق MLAR/EN1363-1 للـ FLS 37']::text[], array['Heights: 17/30/37 mm','Material: pre-galvanised S250GD','Lengths: 2/3/6 m','Fire cert MLAR/EN1363-1 for FLS 37']::text[], 220),
  ('cantilever-arm-alk', 'strut', 'ذراع كونسول ALK', 'Cantilever Arm ALK', 'ذراع تعليق اقتصادي من بروفايل FLS', 'Cost-effective cantilever from FLS profile', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/Cantilever-arm-ALK.png', array['اطوال: 200 / 300 / 450 / 600 مم','لوحة القاعدة: فولاذ E295','القناة: فولاذ S215G وفق DIN 1623','شهادة حريق MLAR/EN1363-1 للـ ALK 37']::text[], array['Lengths: 200/300/450/600 mm','Base plate: steel E295','Channel: S215G per DIN 1623','Fire cert MLAR/EN1363-1 for ALK 37']::text[], 230),
  ('angle-brace-ws-31-45', 'strut', 'دعامة زاوية WS 31-45 درجة', 'Angle Brace WS 31-45 degrees', 'ثبات عال للإنشاءات الداعمة', 'High stability for supporting structures', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/fischer-Angle-brace-WS-31-45%C2%B0.png', array['زاوية التثبيت: 45 درجة','فتحات طويلة قياسية','يتصل بـ FSM Clix P ومسمار','متوافق مع قنوات FLS وأذرع ALK']::text[], array['Fixing angle: 45 degrees','Standardised long slots','Connects via FSM Clix P','Compatible with FLS channels and ALK']::text[], 240),
  ('beam-clamp-tkr-31', 'strut', 'مشبك تعليق على الجسور TKR-31', 'Beam Clamp TKR-31', 'تثبيت قنوات FLS على العوارض الفولاذية', 'Fix FLS channels to steel girders', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/fischer-Clamp-hanger-TKR-31.png', array['بدون لحام او حفر في العارضة','مشبك: فولاذ S235JR','لوحة: فولاذ E295','مشبكان لكل نقطة تثبيت']::text[], array['No welding or drilling','Clamp: steel S235JR','Plate: steel E295','Two clamps per fixing point']::text[], 250),
  ('saddle-flange-sf-l', 'strut', 'فلنشة سرج SF-L', 'Saddle Flange SF-L', 'ربط قنوات FUS بالهيكل بزاوية 90 درجة', 'Connect FUS channels at 90 degrees', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/Saddle-flange-SF-L.png', array['زاوية التركيب: 90 درجة','لوحة قاعدة بفتحات 90 درجة','سرج مطابق لإدخال القناة','متوفر: مجلفن - مغطس ساخن - ستانلس']::text[], array['Installation angle: 90 degrees','Base plate with 90 degree slots','Perfect-fit saddle','Available: zinc - hot-dip - stainless']::text[], 260),
  ('angle-fitting-faf', 'strut', 'وصلة زاوية FAF', 'Angle Fitting FAF', 'وصل قنوات FUS بزوايا متعددة', 'Join FUS channels at multiple angles', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/Angle-fitting-FAF.png', array['2 / 3 / 4 ثقوب بزاوية 90 درجة','3 ثقوب بزاوية 45 درجة','مادة: فولاذ S235JR','FAF مجلفن - FAF hdg خارجي - FAF A4 ستانلس']::text[], array['2/3/4-hole at 90 degrees','3-hole at 45 degrees','Material: S235JR steel','FAF zinc - FAF hdg outdoor - FAF A4 stainless']::text[], 270),
  ('system-connector-fma-fus', 'strut', 'وصلة نظام FMA-FUS', 'System Connector FMA-FUS', 'هياكل متعددة الابعاد من قنوات FUS', 'Multidimensional FUS channel structures', '', '', 'https://osoulalbinaa.com/wp-content/uploads/2026/06/fischer-System-connector-FMA-FUS.png', array['لوحة قاعدة: فولاذ S355 عالي المقاومة','حامل البروفايل: فولاذ S235JR','فتحات طويلة مع شبكة FMHB','يعمل كفلنشة سرج او كزاوية']::text[], array['Base plate: high-strength S355 steel','Profile mount: S235JR steel','Long slots with FMHB grating','Functions as saddle flange or angle']::text[], 280)
on conflict (slug) do nothing;

-- صفُّ سعرٍ لكلّ منتجٍ ليجد المديرُ حقلًا يملؤه — بصفرٍ حتّى يُسعَّر.
insert into public.product_prices (product_id, list_price, partner_price)
select p.id, 0, 0 from public.products p
on conflict (product_id) do nothing;
